version: "3.3"

services:
  comsollm:
    image: docker-comsolflexlmserver
    hostname: ldap.example.com
    mac_address: ab:dc:ef:01:23
    ports:
      - 7018
      - 7019
    deploy:
      mode: replicated
      replicas: 1
    labels:
      - "traefik.1718.frontend.rule=Host:flexlm.example.com"
      - "traefik.1718.port=1718"
      - "traefik.1719.frontend.rule=Host:flexlm.example.com"
      - "traefik.1719.port=1719"
