version: "3.3"

services:
  flexlm:
    image: kdfischer/docker-comsolflexlmserver
    hostname: flexlm.example.com
    mac_address: ba:98:76:54:32:10
    volumes:
      - ./distrib/license.dat:/usr/local/flexlm/licenses/license.dat:ro
    ports:
      - 7018
      - 7019
    deploy:
      mode: replicated
      replicas: 1
    labels:
      - "traefik.1718.frontend.rule=Host:flexlm.example.com"
      - "traefik.1718.port=1718"
      - "traefik.1719.frontend.rule=Host:flexlm.example.com"
      - "traefik.1719.port=1719"
